# Use root/example as user/password credentials
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sinclair
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080